/*
 * @file: otp-verify.js
 * @description: api for verify the otp generated by system
 * @author: Pankaj Pandey
 */
import express from 'express';
import { createValidator } from 'express-joi-validation';
import Joi from '@hapi/joi';
import { checkToken, decryptDataApi } from '../../../utilities/universal';
import { otpVerification } from '../../../controllers/user';
const app = express();
const validator = createValidator({ passError: true });

/**
 * @swagger
 * /api/v1/user/otp-verify:
 *  post:
 *   tags: ["Users"]
 *   summary: otp verification
 *   description: api user to verify the user mobile otp
 *   security:
 *    - OAuth2: []   # Use Authorization
 *   parameters:
 *      - in: header
 *        name: Authorization
 *        type: string
 *        required: true
 *      - in: body
 *        name: user
 *        description: Verify user otp
 *        schema:
 *         type: object
 *         required:
 *          - user add
 *         properties:
 *           OTP:
 *             type: number
 *             required:
 *   responses:
 *    '200':
 *      description: success
 *    '400':
 *      description: fail
 */


const userSchema = Joi.object({
    OTP: Joi.number()
      .required()
      .label('OTP')
  });

app.post(
  '/user/otp-verify',
  //decryptDataApi,
  validator.body(userSchema, {
    joi: { convert: true, allowUnknown: false }
  }),
  checkToken,
  otpVerification
);

export default app;
